In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
dataset=pd.read_csv('Churn_Modelling.csv')
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [5]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))

In [7]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

In [10]:
ann=tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [12]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.3330 - accuracy: 0.8673
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3314 - accuracy: 0.8638
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3469 - accuracy: 0.8583
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3333 - accuracy: 0.8621
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3363 - accuracy: 0.8597
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3252 - accuracy: 0.8683
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3319 - accuracy: 0.8590
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3396 - accuracy: 0.8588
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3438 - accuracy: 0.8571
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3341 - accura

In [13]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 0]]


In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1536   49]
 [ 214  201]]


0.8685